# Generated by Django 4.1.7 on 2023-04-01 18:18

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AssetClass",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="AssetCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("expectancy", models.IntegerField()),
                (
                    "expectancy_unit",
                    models.CharField(
                        choices=[
                            ("DAYS", "days"),
                            ("MONTHS", "months"),
                            ("YEARS", "years"),
                        ],
                        default="YEARS",
                        max_length=10,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "asset_class",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="aaset_class",
                        to="inventory.assetclass",
                    ),
                ),
                (
                    "manager",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="manager",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Asset Category",
                "ordering": ["-created"],
            },
        ),
        migrations.CreateModel(
            name="Asset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tag",
                    models.CharField(blank=True, max_length=50, null=True, unique=True),
                ),
                (
                    "registration",
                    models.CharField(blank=True, max_length=50, null=True, unique=True),
                ),
                ("serial", models.CharField(max_length=50, unique=True)),
                (
                    "purchase_date",
                    models.DateTimeField(
                        blank=True,
                        default=datetime.datetime(2023, 4, 1, 20, 18, 56, 417981),
                        null=True,
                    ),
                ),
                (
                    "received_date",
                    models.DateTimeField(
                        blank=True,
                        default=datetime.datetime(2023, 4, 1, 20, 18, 56, 417981),
                        null=True,
                    ),
                ),
                ("brand", models.CharField(blank=True, max_length=255, null=True)),
                ("colour", models.CharField(blank=True, max_length=255, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("ram", models.CharField(blank=True, max_length=255, null=True)),
                ("ip_address", models.CharField(blank=True, max_length=255, null=True)),
                ("disk_size", models.CharField(blank=True, max_length=255, null=True)),
                ("processor", models.CharField(blank=True, max_length=255, null=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("location", models.CharField(max_length=255, null=True)),
                (
                    "shared_resource",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                (
                    "shared_resource_location",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "condition",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("GOOD", "GOOD"),
                            ("FAIR", "FAIR"),
                            ("BEST", "BEST"),
                            ("N/A", "n/a"),
                        ],
                        max_length=25,
                        null=True,
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=50, null=True
                    ),
                ),
                (
                    "conversion_rate",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=50, null=True
                    ),
                ),
                (
                    "allocated_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="allocated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="category",
                        to="inventory.assetcategory",
                    ),
                ),
                (
                    "current_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="current",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
