# Generated by Django 4.1.7 on 2023-04-02 11:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0005_asset_purchase_order_alter_asset_purchase_date_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="assetsupplier",
            options={
                "verbose_name": "Asset Supplier",
                "verbose_name_plural": "Asset Suppliers",
            },
        ),
        migrations.AddField(
            model_name="assetsupplier",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="asset",
            name="purchase_date",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(2023, 4, 2, 13, 35, 22, 103206),
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="asset",
            name="received_date",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(2023, 4, 2, 13, 35, 22, 103206),
                null=True,
            ),
        ),
    ]
