# Generated by Django 4.1.7 on 2023-04-02 17:27

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "inventory",
            "0007_alter_asset_purchase_date_alter_asset_purchase_order_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="asset",
            name="purchase_date",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(2023, 4, 2, 19, 27, 54, 793990),
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="asset",
            name="received_date",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(2023, 4, 2, 19, 27, 54, 793990),
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="AssetMaintenance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("reason", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "description",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("upgrade", models.BooleanField(default=False)),
                (
                    "asset",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="asset_maintained",
                        to="inventory.asset",
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
    ]
