# Generated by Django 4.1.7 on 2023-04-01 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("company", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="status",
            field=models.ForeignKey(
                blank=True,
                help_text="status",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="company.employeestatus",
            ),
        ),
    ]
